[package]
name = "axum-intro"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6"
lazy-regex = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tower-cookies = "0.9"
tower-http = { version = "0.4", features = ["fs"] }
uuid = { version = "1", features = ["v4", "fast-rng"] }
